routes:
  - id: local_to_aws
    uri: https://at9skp6go9.execute-api.ap-northeast-2.amazonaws.com
    predicates:
      - Path=/fileupload
    filters:
      - StripPrefix=1
      - RemoveRequestHeader=Authorization
      - AddRequestHeader=Authorization, Bearer your_token_here  # Authorization 헤더 추가
      - SetResponseHeader=Access-Control-Allow-Origin, *  # CORS 헤더 설정
      - SetResponseHeader=Access-Control-Allow-Methods, GET, POST, PUT, DELETE

  - id: local_to_server
    uri: http://${COMMON_SERVER_URL:mlops-api.hyo-sunshine.site}:${COMMON_SERVER_PORT:3000}
    predicates:
      - Path=/server-info
    filters:
      - StripPrefix=1
      - SetUriAuthorizationHeader
      - RemoveRequestHeader=Authorization
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Method Access-Control-Request-Headers

 